# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b088276b4cff8828a44c22390a30c0230dc4dcb412cf825dcae776f9d6728791c8fe760bc53d47a7d4c4b4631674b2a4a972734b755c13974697967192f48e9

test:
  secret_key_base: 73fcce931dd04cebdc28a9a7cfeb52f9f13d01dfd6a7bf145321dd039c5638c0af2f47af9b76840e21ba3a80579cc6c4cee66f31fd19596f9368c13ee28e289f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
